// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientCare.DAL;

namespace PatientCare.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200621162749_jjjjj")]
    partial class jjjjj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PatientCare.Entity.AppModel.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Doctor")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeTo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Doctor");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(2591),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(2610),
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3030),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3047),
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3058),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3063),
                            Name = "O"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3067),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3071),
                            Name = "AB"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Doctor")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Doctor");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.CoronaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoronaStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5688),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5705),
                            Name = "Positive"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6101),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6118),
                            Name = "Negative"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6130),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6135),
                            Name = "Low"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6139),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6143),
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6148),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6152),
                            Name = "Severe"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_Gender")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Specialization")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Gender");

                    b.HasIndex("Fk_Specialization");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.DoctorDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Doctor")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Doctor");

                    b.ToTable("DoctorDocuments");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.DonateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonateTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3634),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(3651),
                            Name = "BloodCells"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(4060),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(4077),
                            Name = "Platelets"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(4096),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(4100),
                            Name = "Plasma"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_DonateType")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_DonateType");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(1505),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(1524),
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(1972),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(1989),
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableBeds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_City")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_City");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Chat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDoctor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsViewd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Chat");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OfflineCoronaTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_CoronaStatus")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_CoronaStatus");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("OfflineCoronaTests");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OnlineCoronaTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_CoronaStatus")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_CoronaStatus");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("OnlineCoronaTests");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fk_BloodType")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Gender")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_BloodType");

                    b.HasIndex("Fk_Gender");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.PatientDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("PatientDocuments");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_City")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_City");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(4649),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(4667),
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5066),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5083),
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5095),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5099),
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5104),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5108),
                            Name = "Pulmonologist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5112),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5116),
                            Name = "Nephrology"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5121),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5125),
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5129),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5133),
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5137),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(5141),
                            Name = "Deratology"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 607, DateTimeKind.Unspecified).AddTicks(9367),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 609, DateTimeKind.Unspecified).AddTicks(8196),
                            Name = "FullAccess"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 609, DateTimeKind.Unspecified).AddTicks(9279),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 609, DateTimeKind.Unspecified).AddTicks(9304),
                            Name = "ControlAccess"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 609, DateTimeKind.Unspecified).AddTicks(9323),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 609, DateTimeKind.Unspecified).AddTicks(9328),
                            Name = "ViewAccess"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JopTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6770),
                            Email = "Developer@App.com",
                            FullName = "Developer",
                            IsActive = true,
                            JopTitle = "Developer",
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(6789),
                            Password = "sssr2439uh"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemUserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("Fk_SystemUser")
                        .HasColumnType("int");

                    b.Property<int>("Fk_SystemView")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_AccessLevel");

                    b.HasIndex("Fk_SystemUser");

                    b.HasIndex("Fk_SystemView");

                    b.ToTable("SystemUserPermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 612, DateTimeKind.Unspecified).AddTicks(3390),
                            Fk_AccessLevel = 1,
                            Fk_SystemUser = 1,
                            Fk_SystemView = 1,
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 612, DateTimeKind.Unspecified).AddTicks(3419)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 612, DateTimeKind.Unspecified).AddTicks(4534),
                            Fk_AccessLevel = 1,
                            Fk_SystemUser = 1,
                            Fk_SystemView = 2,
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 612, DateTimeKind.Unspecified).AddTicks(4555)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 612, DateTimeKind.Unspecified).AddTicks(4601),
                            Fk_AccessLevel = 1,
                            Fk_SystemUser = 1,
                            Fk_SystemView = 3,
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 612, DateTimeKind.Unspecified).AddTicks(4606)
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemView");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(224),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(255),
                            Name = "Home"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(799),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(820),
                            Name = "SystemView"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(833),
                            LastModifiedAt = new DateTime(2020, 6, 21, 18, 27, 48, 611, DateTimeKind.Unspecified).AddTicks(873),
                            Name = "SystemUser"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Agenda", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Doctor", "Doctor")
                        .WithMany("Agenda")
                        .HasForeignKey("Fk_Doctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Chat", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Doctor", "Doctor")
                        .WithMany("Chats")
                        .HasForeignKey("Fk_Doctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("Chats")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Doctor", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Gender", "Gender")
                        .WithMany("Doctors")
                        .HasForeignKey("Fk_Gender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("Fk_Specialization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.DoctorDocument", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Doctor", "Doctor")
                        .WithMany("DoctorDocuments")
                        .HasForeignKey("Fk_Doctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Donation", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.DonateType", "DonateType")
                        .WithMany("Donations")
                        .HasForeignKey("Fk_DonateType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("Donations")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Hospital", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.City", "City")
                        .WithMany("Hospitals")
                        .HasForeignKey("Fk_City")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Message", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("Fk_Chat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OfflineCoronaTest", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.CoronaStatus", "CoronaStatus")
                        .WithMany("OfflineCoronaTests")
                        .HasForeignKey("Fk_CoronaStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("OfflineCoronaTests")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OnlineCoronaTest", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.CoronaStatus", "CoronaStatus")
                        .WithMany("OnlineCoronaTests")
                        .HasForeignKey("Fk_CoronaStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("OnlineCoronaTests")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Patient", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.BloodType", "BloodType")
                        .WithMany("Patients")
                        .HasForeignKey("Fk_BloodType");

                    b.HasOne("PatientCare.Entity.AppModel.Gender", "Gender")
                        .WithMany("Patients")
                        .HasForeignKey("Fk_Gender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.PatientDocument", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("PatientDocuments")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Pharmacy", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.City", "City")
                        .WithMany("Pharmacies")
                        .HasForeignKey("Fk_City")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemUserPermission", b =>
                {
                    b.HasOne("PatientCare.Entity.AuthModel.AccessLevel", "AccessLevel")
                        .WithMany("SystemUserPermission")
                        .HasForeignKey("Fk_AccessLevel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AuthModel.SystemUser", "SystemUser")
                        .WithMany("SystemUserPermission")
                        .HasForeignKey("Fk_SystemUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AuthModel.SystemView", "SystemView")
                        .WithMany("SystemUserPermission")
                        .HasForeignKey("Fk_SystemView")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
