// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientCare.DAL;

namespace PatientCare.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200620000638_dmsdkksm")]
    partial class dmsdkksm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PatientCare.Entity.AppModel.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Doctor")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeTo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Doctor");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(2615),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(2633),
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3048),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3065),
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3078),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3082),
                            Name = "O"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3087),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3091),
                            Name = "AB"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Doctor")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Doctor");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.CoronaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoronaStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5833),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5850),
                            Name = "Positive"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6245),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6262),
                            Name = "Negative"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6274),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6279),
                            Name = "Low"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6284),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6288),
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6293),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6297),
                            Name = "Severe"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_Gender")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Specialization")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Gender");

                    b.HasIndex("Fk_Specialization");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.DoctorDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Doctor")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Doctor");

                    b.ToTable("DoctorDocuments");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.DonateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonateTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3751),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(3769),
                            Name = "BloodCells"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(4179),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(4197),
                            Name = "Platelets"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(4215),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(4220),
                            Name = "Plasma"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_DonateType")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_DonateType");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(1539),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(1558),
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(1996),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(2014),
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableBeds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_City")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_City");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Chat")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Chat");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OfflineCoronaTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_CoronaStatus")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_CoronaStatus");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("OfflineCoronaTests");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OnlineCoronaTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_CoronaStatus")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_CoronaStatus");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("OnlineCoronaTests");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fk_BloodType")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Gender")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_BloodType");

                    b.HasIndex("Fk_Gender");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.PatientDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Patient")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Patient");

                    b.ToTable("PatientDocuments");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_City")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_City");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(4773),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(4791),
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5187),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5204),
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5216),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5221),
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5225),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5229),
                            Name = "Pulmonologist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5234),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5238),
                            Name = "Nephrology"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5243),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5247),
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5251),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5255),
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5259),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(5263),
                            Name = "Deratology"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 262, DateTimeKind.Unspecified).AddTicks(7622),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 264, DateTimeKind.Unspecified).AddTicks(8142),
                            Name = "FullAccess"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 264, DateTimeKind.Unspecified).AddTicks(9207),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 264, DateTimeKind.Unspecified).AddTicks(9231),
                            Name = "ControlAccess"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 264, DateTimeKind.Unspecified).AddTicks(9251),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 264, DateTimeKind.Unspecified).AddTicks(9256),
                            Name = "ViewAccess"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JopTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6905),
                            Email = "Developer@App.com",
                            FullName = "Developer",
                            IsActive = true,
                            JopTitle = "Developer",
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(6924),
                            Password = "xooa9473yq"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemUserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("Fk_SystemUser")
                        .HasColumnType("int");

                    b.Property<int>("Fk_SystemView")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Fk_AccessLevel");

                    b.HasIndex("Fk_SystemUser");

                    b.HasIndex("Fk_SystemView");

                    b.ToTable("SystemUserPermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 267, DateTimeKind.Unspecified).AddTicks(3588),
                            Fk_AccessLevel = 1,
                            Fk_SystemUser = 1,
                            Fk_SystemView = 1,
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 267, DateTimeKind.Unspecified).AddTicks(3616)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 267, DateTimeKind.Unspecified).AddTicks(4715),
                            Fk_AccessLevel = 1,
                            Fk_SystemUser = 1,
                            Fk_SystemView = 2,
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 267, DateTimeKind.Unspecified).AddTicks(4736)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 267, DateTimeKind.Unspecified).AddTicks(4771),
                            Fk_AccessLevel = 1,
                            Fk_SystemUser = 1,
                            Fk_SystemView = 3,
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 267, DateTimeKind.Unspecified).AddTicks(4776)
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemView");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(309),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(339),
                            Name = "Home"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(813),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(831),
                            Name = "SystemView"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(844),
                            LastModifiedAt = new DateTime(2020, 6, 20, 2, 6, 38, 266, DateTimeKind.Unspecified).AddTicks(849),
                            Name = "SystemUser"
                        });
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Agenda", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Doctor", "Doctor")
                        .WithMany("Agenda")
                        .HasForeignKey("Fk_Doctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Chat", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Doctor", "Doctor")
                        .WithMany("Chats")
                        .HasForeignKey("Fk_Doctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("Chats")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Doctor", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Gender", "Gender")
                        .WithMany("Doctors")
                        .HasForeignKey("Fk_Gender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("Fk_Specialization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.DoctorDocument", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Doctor", "Doctor")
                        .WithMany("DoctorDocuments")
                        .HasForeignKey("Fk_Doctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Donation", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.DonateType", "DonateType")
                        .WithMany("Donations")
                        .HasForeignKey("Fk_DonateType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("Donations")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Hospital", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.City", "City")
                        .WithMany("Hospitals")
                        .HasForeignKey("Fk_City")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Message", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("Fk_Chat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OfflineCoronaTest", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.CoronaStatus", "CoronaStatus")
                        .WithMany("OfflineCoronaTests")
                        .HasForeignKey("Fk_CoronaStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("OfflineCoronaTests")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.OnlineCoronaTest", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.CoronaStatus", "CoronaStatus")
                        .WithMany("OnlineCoronaTests")
                        .HasForeignKey("Fk_CoronaStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("OnlineCoronaTests")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Patient", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.BloodType", "BloodType")
                        .WithMany("Patients")
                        .HasForeignKey("Fk_BloodType");

                    b.HasOne("PatientCare.Entity.AppModel.Gender", "Gender")
                        .WithMany("Patients")
                        .HasForeignKey("Fk_Gender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.PatientDocument", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.Patient", "Patient")
                        .WithMany("PatientDocuments")
                        .HasForeignKey("Fk_Patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AppModel.Pharmacy", b =>
                {
                    b.HasOne("PatientCare.Entity.AppModel.City", "City")
                        .WithMany("Pharmacies")
                        .HasForeignKey("Fk_City")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCare.Entity.AuthModel.SystemUserPermission", b =>
                {
                    b.HasOne("PatientCare.Entity.AuthModel.AccessLevel", "AccessLevel")
                        .WithMany("SystemUserPermission")
                        .HasForeignKey("Fk_AccessLevel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AuthModel.SystemUser", "SystemUser")
                        .WithMany("SystemUserPermission")
                        .HasForeignKey("Fk_SystemUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCare.Entity.AuthModel.SystemView", "SystemView")
                        .WithMany("SystemUserPermission")
                        .HasForeignKey("Fk_SystemView")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
